languae: python
python:
  - "3.7"

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - chmod 777 .
  - docker-compose run --rm web bin/wait-for-postgres.sh coverage run --source=. manage.py test


after_script:
  # Log DB output in case issues occurred where this can help us debug quicly
  - docker-compose logs db

  # upload coverage report
  - bash <(curl -s https://codecov.io/bash)
